export const idleTimeout = 1000 * 60 * 45; // in Milliseconds

export const EMM_DISTRACTION_TOOLTIP = 'Distraction Index consists of evidence-based audible and visual distractions such as conversation and machine alarms. The Distraction Index has a range between 0 and 100, with an average procedure having a Distraction Index of 30, and greater scores indicative of more distracting operating room environments.';
export const EMM_TECHNICAL_TOOLTIP = 'Performance Index consists of evidence-based components such as time based metrics, measures of manual dexterity and intraoperative adverse events. The Performance Index has a range between 0 and 100. An average procedure will have a Performance Index of 70, with higher scores indicative of better performance.'
export const EMM_ADVERSEEVENT_TOOLTIP = 'Adverse Event Rate is the number of intraoperative adverse events that occured per hour of surgical procedure.';

export const HL7_DATA = {
	"hypotension": {
		"assets": null,
		"body": "Blood Pressure data was transmitted for 55% of the procedure.",
		"dataPoints": [{
			"active": null,
			"description": null,
			"note": "#FF4D4D",
			"subTitle": null,
			"title": null,
			"valueX": "<65.0",
			"valueY": "1",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#6EDE95",
			"subTitle": null,
			"title": null,
			"valueX": "<75.0",
			"valueY": "0",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#6EDE95",
			"subTitle": null,
			"title": null,
			"valueX": "<85.0",
			"valueY": "4",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#6EDE95",
			"subTitle": null,
			"title": null,
			"valueX": "<95.0",
			"valueY": "4",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#6EDE95",
			"subTitle": null,
			"title": null,
			"valueX": "<105.0",
			"valueY": "1",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#6EDE95",
			"subTitle": null,
			"title": null,
			"valueX": "<115.0",
			"valueY": "0",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#6EDE95",
			"subTitle": null,
			"title": null,
			"valueX": "<125.0",
			"valueY": "0",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#6EDE95",
			"subTitle": null,
			"title": null,
			"valueX": ">125.0",
			"valueY": "0",
			"valueZ": null
		}],
		"description": "medium",
		"endTime": null,
		"footer": null,
		"group": null,
		"groupOrder": null,
		"header": "mmHg",
		"order": null,
		"startTime": null,
		"subTitle": "Blood Pressure Distribution (mmHg)",
		"tileType": null,
		"title": "Hypotension",
		"total": "10"
	},
	"hypothermia": {
		"assets": null,
		"body": "Temperature data was transmitted for 100% of the procedure.",
		"dataPoints": [{
			"active": null,
			"description": null,
			"note": "#FF4D4D",
			"subTitle": null,
			"title": null,
			"valueX": "<34.0",
			"valueY": "0",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#FF4D4D",
			"subTitle": null,
			"title": null,
			"valueX": "<34.5",
			"valueY": "0",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#FF4D4D",
			"subTitle": null,
			"title": null,
			"valueX": "<35.0",
			"valueY": "0",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#FF4D4D",
			"subTitle": null,
			"title": null,
			"valueX": "<35.5",
			"valueY": "111",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#FF4D4D",
			"subTitle": null,
			"title": null,
			"valueX": "<36.0",
			"valueY": "196",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#6EDE95",
			"subTitle": null,
			"title": null,
			"valueX": "<36.5",
			"valueY": "149",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#6EDE95",
			"subTitle": null,
			"title": null,
			"valueX": "<37.0",
			"valueY": "0",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#6EDE95",
			"subTitle": null,
			"title": null,
			"valueX": ">37.0",
			"valueY": "1",
			"valueZ": null
		}],
		"description": "fast",
		"endTime": null,
		"footer": null,
		"group": null,
		"groupOrder": null,
		"header": "C",
		"order": null,
		"startTime": null,
		"subTitle": "Temperature Distribution (C)",
		"tileType": null,
		"title": "Hypothermia",
		"total": "67"
	},
	"hypoxia": {
		"assets": null,
		"body": "Blood Oxygenation data was transmitted for 100% of the procedure.",
		"dataPoints": [{
			"active": null,
			"description": null,
			"note": "#FF4D4D",
			"subTitle": null,
			"title": null,
			"valueX": "<88.0",
			"valueY": "0",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#FF4D4D",
			"subTitle": null,
			"title": null,
			"valueX": "<89.5",
			"valueY": "0",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#FF4D4D",
			"subTitle": null,
			"title": null,
			"valueX": "<91.0",
			"valueY": "0",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#FF4D4D",
			"subTitle": null,
			"title": null,
			"valueX": "<92.5",
			"valueY": "1",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#FF4D4D",
			"subTitle": null,
			"title": null,
			"valueX": "<94.0",
			"valueY": "0",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#6EDE95",
			"subTitle": null,
			"title": null,
			"valueX": "<95.5",
			"valueY": "2",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#6EDE95",
			"subTitle": null,
			"title": null,
			"valueX": "<97.0",
			"valueY": "106",
			"valueZ": null
		}, {
			"active": null,
			"description": null,
			"note": "#6EDE95",
			"subTitle": null,
			"title": null,
			"valueX": ">97.0",
			"valueY": "349",
			"valueZ": null
		}],
		"description": "fast",
		"endTime": null,
		"footer": null,
		"group": null,
		"groupOrder": null,
		"header": "%",
		"order": null,
		"startTime": null,
		"subTitle": "Blood Oxygenation Distribution (%)",
		"tileType": null,
		"title": "Hypoxia",
		"total": "0"
	}
};